import { mutation, query, internalMutation, internalQuery } from './_generated/server';
import { v } from 'convex/values';
import { authComponent } from './auth';

/**
 * Get a single message by ID (internal use for agent updates)
 */
export const get = internalQuery({
	args: { id: v.id('messages') },
	handler: async (ctx, { id }) => {
		return await ctx.db.get(id);
	}
});

/**
 * Lists all messages for a specific chat thread.
 *
 * Verifies that the authenticated user owns the thread before returning messages.
 * Each message includes a list of signed URLs for any attached images.
 *
 * @param threadId - The unique identifier of the chat thread.
 * @returns A list of messages with associated image URLs.
 */
export const list = query({
	args: { threadId: v.id('threads') },
	handler: async (ctx, { threadId }) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) return [];

		// Verify user owns this thread
		const thread = await ctx.db.get(threadId);
		if (!thread || thread.userId !== user._id) return [];

		const messages = await ctx.db
			.query('messages')
			.withIndex('by_thread', (q) => q.eq('threadId', threadId))
			.collect();

		return Promise.all(
			messages.map(async (msg) => {
				const imageUrls = await Promise.all(
					(msg.images || []).map((storageId) => ctx.storage.getUrl(storageId))
				);
				return {
					...msg,
					imageUrls: imageUrls.filter((url) => url !== null) as string[],
					deletedImageCount: msg.deletedImages?.length || 0
				};
			})
		);
	}
});

/**
 * Sends a new message in a chat thread.
 *
 * Verifies that the authenticated user owns the thread.
 * Updates the thread's `updatedAt` timestamp.
 *
 * @param body - The text content of the message.
 * @param reasoning - Optional. The reasoning content if generated by an AI.
 * @param threadId - The unique identifier of the chat thread.
 * @param role - The role of the message sender ('user' or 'assistant').
 * @throws {Error} if the user is not authenticated or the thread is not found/unauthorized.
 */
export const send = mutation({
	args: {
		body: v.string(),
		reasoning: v.optional(v.string()),
		threadId: v.id('threads'),
		role: v.union(v.literal('user'), v.literal('assistant'))
	},
	handler: async (ctx, { body, reasoning, threadId, role }) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) {
			throw new Error('Not authenticated');
		}

		// Verify user owns this thread
		const thread = await ctx.db.get(threadId);
		if (!thread || thread.userId !== user._id) {
			throw new Error('Thread not found or unauthorized');
		}

		await ctx.db.insert('messages', {
			body,
			reasoning,
			userId: user._id,
			threadId,
			role,
			createdAt: Date.now()
		});

		await ctx.db.patch(threadId, { updatedAt: Date.now() });
	}
});

/**
 * Internal mutation to create a message.
 *
 * Used by background actions like AI generation to store messages without direct user authentication.
 *
 * @param body - The text content of the message.
 * @param reasoning - Optional. The reasoning content.
 * @param userId - The ID of the user owning the message.
 * @param threadId - The ID of the thread.
 * @param role - The role of the message sender.
 * @param model - Optional. The AI model used.
 * @param metadata - Optional. Additional metadata for the message.
 * @returns The ID of the newly created message.
 */
export const internalCreate = internalMutation({
	args: {
		body: v.string(),
		reasoning: v.optional(v.string()),
		userId: v.string(),
		threadId: v.id('threads'),
		role: v.union(v.literal('user'), v.literal('assistant')),
		model: v.optional(v.string()),
		metadata: v.optional(v.any())
	},
	handler: async (ctx, args) => {
		const id = await ctx.db.insert('messages', {
			...args,
			createdAt: Date.now()
		});
		await ctx.db.patch(args.threadId, { updatedAt: Date.now() });
		return id;
	}
});

/**
 * Internal mutation to update an existing message.
 *
 * Used for streaming updates and storing final metadata like usage and cost.
 *
 * @param messageId - The ID of the message to update.
 * @param body - The updated text content.
 * @param usage - Optional. AI token usage statistics.
 * @param cost - Optional. The estimated cost of the generation.
 * @param metadata - Optional. Updated metadata.
 * @param reasoning - Optional. Updated reasoning content.
 * @param isCancelled - Optional. Whether the generation was cancelled.
 * @param images - Optional. Associated storage IDs for generated images.
 */
export const internalUpdate = internalMutation({
	args: {
		messageId: v.id('messages'),
		body: v.string(),
		usage: v.optional(
			v.object({
				promptTokens: v.number(),
				completionTokens: v.number(),
				totalTokens: v.number()
			})
		),
		cost: v.optional(v.number()),
		metadata: v.optional(v.any()),
		reasoning: v.optional(v.string()),
		isCancelled: v.optional(v.boolean()),
		images: v.optional(v.array(v.id('_storage')))
	},
	handler: async (
		ctx,
		{ messageId, body, usage, cost, metadata, reasoning, isCancelled, images }
	) => {
		// Check if message exists before updating to avoid crashing background actions
		const existing = await ctx.db.get(messageId);
		if (!existing) {
			console.warn(`[Messages] internalUpdate: Message ${messageId} not found, skipping update`);
			return;
		}

		const updates: any = { body };
		if (usage) updates.usage = usage;
		if (cost !== undefined) updates.cost = cost;
		if (metadata) updates.metadata = metadata;
		if (reasoning !== undefined) updates.reasoning = reasoning;
		if (isCancelled !== undefined) updates.isCancelled = isCancelled;
		if (images !== undefined) updates.images = images;
		await ctx.db.patch(messageId, updates);
	}
});

/**
 * Internal mutation to record which memories were added based on this message.
 *
 * Updates the message metadata to track extracted memories.
 *
 * @param messageId - The ID of the message.
 * @param memories - A list of memories (text and category) extracted from the message.
 */
export const internalAppendMemories = internalMutation({
	args: {
		messageId: v.id('messages'),
		memories: v.array(v.object({ text: v.string(), category: v.string() }))
	},
	handler: async (ctx, { messageId, memories }) => {
		const message = await ctx.db.get(messageId);
		if (!message) return;

		const metadata = message.metadata || {};
		await ctx.db.patch(messageId, {
			metadata: {
				...metadata,
				memoriesAdded: memories
			}
		});
	}
});

/**
 * Signals that a message generation should be cancelled.
 *
 * Inserts a record into the `cancellations` table, which background actions poll.
 *
 * @param messageId - The ID of the message to cancel.
 * @throws {Error} if the user is not authenticated.
 */
export const cancel = mutation({
	args: { messageId: v.id('messages') },
	handler: async (ctx, { messageId }) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) throw new Error('Unauthorized');

		const message = await ctx.db.get(messageId);
		if (!message || message.userId !== user._id) return;

		// Move signal to a separate table to avoid OptimisticConcurrencyControlFailure
		const existing = await ctx.db
			.query('cancellations')
			.withIndex('by_message', (q) => q.eq('messageId', messageId))
			.unique();

		if (!existing) {
			await ctx.db.insert('cancellations', { messageId });
		}
	}
});

/**
 * Checks if a specific message generation has been cancelled.
 *
 * @param messageId - The ID of the message to check.
 * @returns A boolean indicating if a cancellation signal exists.
 */
export const checkCancelled = query({
	args: { messageId: v.id('messages') },
	handler: async (ctx, { messageId }) => {
		const user = await authComponent.getAuthUser(ctx);
		const message = await ctx.db.get(messageId);
		if (!message || (user && message.userId !== user._id)) return false;

		// Check if cancellation exists
		const cancellation = await ctx.db
			.query('cancellations')
			.withIndex('by_message', (q) => q.eq('messageId', messageId))
			.unique();
		return !!cancellation;
	}
});

/**
 * Internal mutation to clean up cancellation records once handled.
 *
 * @param messageId - The ID of the message whose cancellation signal should be removed.
 */
export const internalCleanupCancellation = internalMutation({
	args: { messageId: v.id('messages') },
	handler: async (ctx, { messageId }) => {
		const cancellation = await ctx.db
			.query('cancellations')
			.withIndex('by_message', (q) => q.eq('messageId', messageId))
			.unique();
		if (cancellation) {
			await ctx.db.delete(cancellation._id);
		}
	}
});
